### ISSUE TITLE
현재 막힌듯 한데 업데이트 예정 없나요? 

### ISSUE THREAD

**Issue by adunStudio** [geeksbaek/goinside-gallog-cleaner#1]
코드가하나 수시로 바뀐다고 들었는데.. 이부분은 업데이트 할 예정 없나요?

**Comment by geeksbaek** [comment]
예 예정에 없습니다.

Pull Request를 주신다면 반영하겠습니다.

2017년 2월 6일 (월) 오전 12:39, OppaCoding <notifications@github.com>님이 작성:
