### ISSUE TITLE
윈도우 10 64 bit 쓰는데 도중에 클리너가 아무 말도 없이 종료되는 건 버그인가요?

### ISSUE THREAD

**Issue by dfasfsdfdas** [geeksbaek/goinside-gallog-cleaner#2]
가뜩이나 외국이라서 인터넷 속도가 느려서 지우는 데 시간 걸리던데
켜놓고 딴 거 하다 보니까 걍 꺼져 있네요?

**Comment by geeksbaek** [comment]
해당 문제에 대한 오류 메시지가 필요합니다.

.exe 파일을 더블클릭으로 실행하는 대신 커맨드라인에서 실행시키면 프로그램이 종료되더라도 창이 닫히지 않고 오류 메시지가 출력되리라 생각됩니다.

커맨드라인에서 실행시켜보시고 오류 메시지가 출력되면 알려주세요.

**Comment by dfasfsdfdas** [comment]
017/08/16 19:06:23 net/http: request canceled (Client.Timeout exceeded while reading body)

외국의 느린 회선 문제인 거 같기는 합니다만...

**Comment by geeksbaek** [comment]
해당 문제가 발생하는 것으로 추측되는 부분을 goinside 라이브러리에서 수정했습니다. https://github.com/geeksbaek/goinside/commit/64ba59267744730899b51e7621cd97cfa5d54590

수정된 바이너리는 1.1.3 버전으로 다시 업로드했습니다. https://github.com/geeksbaek/goinside-gallog-cleaner/releases/tag/1.1.3

이 버그는 제 테스트 계정으로 재현하기 어렵기 때문에, 이 버그가 고쳐졌는지 테스트를 하지 못했습니다. 다시 문제가 발생하면 알려주세요.
