### ISSUE TITLE
로그인 명령어 있나요?

### ISSUE THREAD

**Issue by pppaapp** [geeksbaek/goinside-gallog-cleaner#5]
mysql처럼
mysql -u 유저 -p 비번
이린식으로 로그인 할 수 있으면 편할거같아요

**Comment by geeksbaek** [comment]
지금은 지원하지 않습니다.

원래 flag를 통한 옵션으로 로그인하는 방식이었다가, 지금처럼 표준입력으로 로그인하는 방식으로 변경하였습니다.

**Comment by pppaapp** [comment]
지원 할 계획은 없으신가요?

**Comment by geeksbaek** [comment]
다음 버전에 추가하는 것을 고려해보겠습니다.

**Comment by pppaapp** [comment]
감사합니다
