### ISSUE TITLE
로그인성공해 검색까지는 하는데 멈추는 문제가 있어요

### ISSUE THREAD

**Issue by kwakhololo** [geeksbaek/goinside-gallog-cleaner#7]
로그인 성공 메세지가 뜨고 딱 50번째 갤로그 페이지 읽고는
글0개 댓글0개 불러오기 성공후
삭제 0/?[------------------
삭제가 끝났습니다

이런식으로 되서 들어가보면 삭제는 안되있는데 뭔가 잘못 설정한건가요??

**Comment by geeksbaek** [comment]
현재 버전에서도 해당 문제가 재현된다면 이슈를 다시 열어주세요
